### PR TITLE
Open PhotoSwipeGallery via props

### PR DESCRIPTION
**Pull request by lachlangordon**
Hi there,

This is a pretty simple addition. We are using this package in our project and we needed a way to open a PhotoSwipeGallery with another element, such as a button. This PR enables you to be able to pass isOpen as a prop to a PhotoSwipeGallery, similar to the behaviour of the PhotoSwipe component.

Thanks,
Lachlan Gordon

### CODE REVIEW

**Comment by mstriemer** [comment]
I'd also like something similar to this, but I just need the `onClose` callback that you added.

I'm laying out the gallery view in a horizontal scrolling pane and I'd like to update its position so the last image is in view when closed. I might need more than just the callback but this looks like a step in the right direction for me too.

**Comment by lachlangordon** [comment]
Oops, one debug log always gets through 😛

**Comment by DannyStaten** [comment]
I would really like this to be merged.

**Comment by minhtranite** [comment]
Thanks for your PS. I have merged it manually. https://github.com/minhtranite/react-photoswipe/commit/215d3d4e97675f14e24dc670c2589139162363cc

**Pull request closed without merging**
